.TH "AccelMeasurement" 3 "Version 1.0" "RedshiftLabls UM7 library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AccelMeasurement \- Structure to hold accelerometer measurement data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Redshift_UML7\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBaccelX\fP"
.br
.RI "Raw accelerometer X-axis data\&. "
.ti -1c
.RI "int16_t \fBaccelY\fP"
.br
.RI "Raw accelerometer Y-axis data\&. "
.ti -1c
.RI "int16_t \fBaccelZ\fP"
.br
.RI "Raw accelerometer Z-axis data\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure to hold accelerometer measurement data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RedshiftLabls UM7 library from the source code\&.
