.TH "GyroMeasurement" 3 "Version 1.0" "RedshiftLabls UM7 library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GyroMeasurement \- Structure to hold gyro measurement data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Redshift_UML7\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBgyroX\fP"
.br
.RI "Processed gyro X-axis data\&. "
.ti -1c
.RI "float \fBgyroY\fP"
.br
.RI "Processed gyro Y-axis data\&. "
.ti -1c
.RI "float \fBgyroZ\fP"
.br
.RI "Processed gyro Z-axis data\&. "
.ti -1c
.RI "float \fBgyroTime\fP"
.br
.RI "Timestamp of the gyro data\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure to hold gyro measurement data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RedshiftLabls UM7 library from the source code\&.
