.TH "MagMeasurement" 3 "Version 1.0" "RedshiftLabls UM7 library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MagMeasurement \- Structure to hold magnetometer measurement data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Redshift_UML7\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBmagX\fP"
.br
.RI "Raw magnetometer X-axis data\&. "
.ti -1c
.RI "int16_t \fBmagY\fP"
.br
.RI "Raw magnetometer Y-axis data\&. "
.ti -1c
.RI "int16_t \fBmagZ\fP"
.br
.RI "Raw magnetometer Z-axis data\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure to hold magnetometer measurement data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RedshiftLabls UM7 library from the source code\&.
