.TH "lib/Redshift_UML7/src/Redshift_UML7.h" 3 "Version 1.0" "RedshiftLabls UM7 library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Redshift_UML7/src/Redshift_UML7.h \- Header file for the \fBRedshift_UML7\fP class, which provides an interface to the UM7 sensor\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <Arduino\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <stddef\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBUM7_packet_struct\fP"
.br
.RI "Structure for holding received packet information\&. "
.ti -1c
.RI "struct \fBGyroMeasurement\fP"
.br
.RI "Structure to hold gyro measurement data\&. "
.ti -1c
.RI "struct \fBAccelMeasurement\fP"
.br
.RI "Structure to hold accelerometer measurement data\&. "
.ti -1c
.RI "struct \fBMagMeasurement\fP"
.br
.RI "Structure to hold magnetometer measurement data\&. "
.ti -1c
.RI "class \fBRedshift_UML7\fP"
.br
.RI "Class to interface with the UM7 sensor\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCREG_COM_SETTINGS\fP   0x00"
.br
.RI "Baud rates for reading over the UM7, default 115200 baud\&. "
.ti -1c
.RI "#define \fBCREG_COM_RATES1\fP   0x01"
.br
.RI "Individual raw data rate\&. "
.ti -1c
.RI "#define \fBCREG_COM_RATES2\fP   0x02"
.br
.RI "All raw data rate\&. "
.ti -1c
.RI "#define \fBCREG_COM_RATES3\fP   0x03"
.br
.RI "Individual processed data rate\&. "
.ti -1c
.RI "#define \fBCREG_COM_RATES4\fP   0x04"
.br
.RI "All processed data rate\&. "
.ti -1c
.RI "#define \fBCREG_COM_RATES5\fP   0x05"
.br
.RI "Quaternion, Euler, position, and velocity data rate\&. "
.ti -1c
.RI "#define \fBCREG_COM_RATES6\fP   0x06"
.br
.RI "Pose (Euler & position), health, and gyro bias estimate rates\&. "
.ti -1c
.RI "#define \fBCREG_COM_RATES7\fP   0x07"
.br
.RI "Data rate for CHR NMEA-style packets\&. "
.ti -1c
.RI "#define \fBCREG_MISC_SETTINGS\fP   0x08"
.br
.RI "Filter and sensor control options\&. "
.ti -1c
.RI "#define \fBCREG_HOME_NORTH\fP   0x09"
.br
.RI "Sets north from current position\&. "
.ti -1c
.RI "#define \fBCREG_HOME_EAST\fP   0x0A"
.br
.RI "Sets east from current position\&. "
.ti -1c
.RI "#define \fBCREG_HOME_UP\fP   0x0B"
.br
.RI "Sets home altitude in meters\&. "
.ti -1c
.RI "#define \fBCREG_GYRO_TRIM_X\fP   0x0C"
.br
.RI "Gyroscope X-axis trim\&. "
.ti -1c
.RI "#define \fBCREG_GYRO_TRIM_Y\fP   0x0D"
.br
.RI "Gyroscope Y-axis trim\&. "
.ti -1c
.RI "#define \fBCREG_GYRO_TRIM_Z\fP   0x0E"
.br
.RI "Gyroscope Z-axis trim\&. "
.ti -1c
.RI "#define \fBCREG_MAG_CAL1_1\fP   0x0F"
.br
.RI "Magnetometer calibration matrix element 1,1\&. "
.ti -1c
.RI "#define \fBCREG_MAG_CAL1_2\fP   0x10"
.br
.RI "Magnetometer calibration matrix element 1,2\&. "
.ti -1c
.RI "#define \fBCREG_MAG_CAL1_3\fP   0x11"
.br
.RI "Magnetometer calibration matrix element 1,3\&. "
.ti -1c
.RI "#define \fBCREG_MAG_CAL2_1\fP   0x12"
.br
.RI "Magnetometer calibration matrix element 2,1\&. "
.ti -1c
.RI "#define \fBCREG_MAG_CAL2_2\fP   0x13"
.br
.RI "Magnetometer calibration matrix element 2,2\&. "
.ti -1c
.RI "#define \fBCREG_MAG_CAL2_3\fP   0x14"
.br
.RI "Magnetometer calibration matrix element 2,3\&. "
.ti -1c
.RI "#define \fBCREG_MAG_CAL3_1\fP   0x15"
.br
.RI "Magnetometer calibration matrix element 3,1\&. "
.ti -1c
.RI "#define \fBCREG_MAG_CAL3_2\fP   0x16"
.br
.RI "Magnetometer calibration matrix element 3,2\&. "
.ti -1c
.RI "#define \fBCREG_MAG_CAL3_3\fP   0x17"
.br
.RI "Magnetometer calibration matrix element 3,3\&. "
.ti -1c
.RI "#define \fBCREG_MAG_BIAS_X\fP   0x18"
.br
.RI "Magnetometer X-axis bias\&. "
.ti -1c
.RI "#define \fBCREG_MAG_BIAS_Y\fP   0x19"
.br
.RI "Magnetometer Y-axis bias\&. "
.ti -1c
.RI "#define \fBCREG_MAG_BIAS_Z\fP   0x1A"
.br
.RI "Magnetometer Z-axis bias\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_CAL1_1\fP   0x1B"
.br
.RI "Accelerometer calibration matrix element 1,1\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_CAL1_2\fP   0x1C"
.br
.RI "Accelerometer calibration matrix element 1,2\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_CAL1_3\fP   0x1D"
.br
.RI "Accelerometer calibration matrix element 1,3\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_CAL2_1\fP   0x1E"
.br
.RI "Accelerometer calibration matrix element 2,1\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_CAL2_2\fP   0x1F"
.br
.RI "Accelerometer calibration matrix element 2,2\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_CAL2_3\fP   0x20"
.br
.RI "Accelerometer calibration matrix element 2,3\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_CAL3_1\fP   0x21"
.br
.RI "Accelerometer calibration matrix element 3,1\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_CAL3_2\fP   0x22"
.br
.RI "Accelerometer calibration matrix element 3,2\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_CAL3_3\fP   0x23"
.br
.RI "Accelerometer calibration matrix element 3,3\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_BIAS_X\fP   0x24"
.br
.RI "Accelerometer X-axis bias\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_BIAS_Y\fP   0x25"
.br
.RI "Accelerometer Y-axis bias\&. "
.ti -1c
.RI "#define \fBCREG_ACCEL_BIAS_Z\fP   0x26"
.br
.RI "Accelerometer Z-axis bias\&. "
.ti -1c
.RI "#define \fBDREG_HEALTH\fP   0x55"
.br
.RI "Health register\&. "
.ti -1c
.RI "#define \fBDREG_GYRO_RAW_XY\fP   0x56"
.br
.RI "Raw gyroscope X and Y-axis data\&. "
.ti -1c
.RI "#define \fBDREG_GYRO_RAW_Z\fP   0x57"
.br
.RI "Raw gyroscope Z-axis data\&. "
.ti -1c
.RI "#define \fBDREG_GYRO_RAW_TIME\fP   0x58"
.br
.RI "Timestamp for raw gyroscope data\&. "
.ti -1c
.RI "#define \fBDREG_ACCEL_RAW_XY\fP   0x59"
.br
.RI "Raw accelerometer X and Y-axis data\&. "
.ti -1c
.RI "#define \fBDREG_ACCEL_RAW_Z\fP   0x5A"
.br
.RI "Raw accelerometer Z-axis data\&. "
.ti -1c
.RI "#define \fBDREG_ACCEL_RAW_TIME\fP   0x5B"
.br
.RI "Timestamp for raw accelerometer data\&. "
.ti -1c
.RI "#define \fBDREG_MAG_RAW_XY\fP   0x5C"
.br
.RI "Raw magnetometer X and Y-axis data\&. "
.ti -1c
.RI "#define \fBDREG_MAG_RAW_Z\fP   0x5D"
.br
.RI "Raw magnetometer Z-axis data\&. "
.ti -1c
.RI "#define \fBDREG_MAG_RAW_TIME\fP   0x5E"
.br
.RI "Timestamp for raw magnetometer data\&. "
.ti -1c
.RI "#define \fBDREG_TEMPERATURE\fP   0x5F"
.br
.RI "Temperature data\&. "
.ti -1c
.RI "#define \fBDREG_TEMPERATURE_TIME\fP   0x60"
.br
.RI "Timestamp for temperature data\&. "
.ti -1c
.RI "#define \fBDREG_GYRO_PROC_X\fP   0x61"
.br
.RI "Processed gyroscope X-axis data (deg/s) "
.ti -1c
.RI "#define \fBDREG_GYRO_PROC_Y\fP   0x62"
.br
.RI "Processed gyroscope Y-axis data (deg/s) "
.ti -1c
.RI "#define \fBDREG_GYRO_PROC_Z\fP   0x63"
.br
.RI "Processed gyroscope Z-axis data (deg/s) "
.ti -1c
.RI "#define \fBDREG_GYRO_PROC_TIME\fP   0x64"
.br
.RI "Timestamp for processed gyroscope data\&. "
.ti -1c
.RI "#define \fBDREG_ACCEL_PROC_X\fP   0x65"
.br
.RI "Processed accelerometer X-axis data (m/s^2) "
.ti -1c
.RI "#define \fBDREG_ACCEL_PROC_Y\fP   0x66"
.br
.RI "Processed accelerometer Y-axis data (m/s^2) "
.ti -1c
.RI "#define \fBDREG_ACCEL_PROC_Z\fP   0x67"
.br
.RI "Processed accelerometer Z-axis data (m/s^2) "
.ti -1c
.RI "#define \fBDREG_ACCEL_PROC_TIME\fP   0x68"
.br
.RI "Timestamp for processed accelerometer data\&. "
.ti -1c
.RI "#define \fBDREG_MAG_PROC_X\fP   0x69"
.br
.RI "Processed magnetometer X-axis data (T) "
.ti -1c
.RI "#define \fBDREG_MAG_PROC_Y\fP   0x6A"
.br
.RI "Processed magnetometer Y-axis data (T) "
.ti -1c
.RI "#define \fBDREG_MAG_PROC_Z\fP   0x6B"
.br
.RI "Processed magnetometer Z-axis data (T) "
.ti -1c
.RI "#define \fBDREG_MAG_PROC_TIME\fP   0x6C"
.br
.RI "Timestamp for processed magnetometer data\&. "
.ti -1c
.RI "#define \fBDREG_QUAT_AB\fP   0x6D"
.br
.RI "Quaternion components A and B\&. "
.ti -1c
.RI "#define \fBDREG_QUAT_CD\fP   0x6E"
.br
.RI "Quaternion components C and D\&. "
.ti -1c
.RI "#define \fBDREG_QUAT_TIME\fP   0x6F"
.br
.RI "Timestamp for quaternion data\&. "
.ti -1c
.RI "#define \fBDREG_EULER_PHI_THETA\fP   0x70"
.br
.RI "Euler angles phi and theta (deg) "
.ti -1c
.RI "#define \fBDREG_EULER_PSI\fP   0x71"
.br
.RI "Euler angle psi (deg) "
.ti -1c
.RI "#define \fBDREG_EULER_PHI_THETA_DOT\fP   0x72"
.br
.RI "Euler angle rates phi and theta (deg/s) "
.ti -1c
.RI "#define \fBDREG_EULER_PSI_DOT\fP   0x73"
.br
.RI "Euler angle rate psi (deg/s) "
.ti -1c
.RI "#define \fBDREG_EULER_TIME\fP   0x74"
.br
.RI "Timestamp for Euler angle data\&. "
.ti -1c
.RI "#define \fBDREG_POSITION_N\fP   0x75"
.br
.RI "Position north (m) "
.ti -1c
.RI "#define \fBDREG_POSITION_E\fP   0x76"
.br
.RI "Position east (m) "
.ti -1c
.RI "#define \fBDREG_POSITION_UP\fP   0x77"
.br
.RI "Position up (m) "
.ti -1c
.RI "#define \fBDREG_POSITION_TIME\fP   0x78"
.br
.RI "Timestamp for position data\&. "
.ti -1c
.RI "#define \fBDREG_VELOCITY_N\fP   0x79"
.br
.RI "Velocity north (m/s) "
.ti -1c
.RI "#define \fBDREG_VELOCITY_E\fP   0x7A"
.br
.RI "Velocity east (m/s) "
.ti -1c
.RI "#define \fBDREG_VELOCITY_UP\fP   0x7B"
.br
.RI "Velocity up (m/s) "
.ti -1c
.RI "#define \fBDREG_VELOCITY_TIME\fP   0x7C"
.br
.RI "Timestamp for velocity data\&. "
.ti -1c
.RI "#define \fBDREG_GPS_LATITUDE\fP   0x7D"
.br
.RI "GPS latitude (deg) "
.ti -1c
.RI "#define \fBDREG_GPS_LONGITUDE\fP   0x7E"
.br
.RI "GPS longitude (deg) "
.ti -1c
.RI "#define \fBDREG_GPS_ALTITUDE\fP   0x7F"
.br
.RI "GPS altitude (m) "
.ti -1c
.RI "#define \fBDREG_GPS_COURSE\fP   0x80"
.br
.RI "GPS course (deg) "
.ti -1c
.RI "#define \fBDREG_GPS_SPEED\fP   0x81"
.br
.RI "GPS speed (m/s) "
.ti -1c
.RI "#define \fBDREG_GPS_TIME\fP   0x82"
.br
.RI "GPS time\&. "
.ti -1c
.RI "#define \fBDREG_GPS_SAT_1_2\fP   0x83"
.br
.RI "GPS satellites 1 and 2\&. "
.ti -1c
.RI "#define \fBDREG_GPS_SAT_3_4\fP   0x84"
.br
.RI "GPS satellites 3 and 4\&. "
.ti -1c
.RI "#define \fBDREG_GPS_SAT_5_6\fP   0x85"
.br
.RI "GPS satellites 5 and 6\&. "
.ti -1c
.RI "#define \fBDREG_GPS_SAT_7_8\fP   0x86"
.br
.RI "GPS satellites 7 and 8\&. "
.ti -1c
.RI "#define \fBDREG_GPS_SAT_9_10\fP   0x87"
.br
.RI "GPS satellites 9 and 10\&. "
.ti -1c
.RI "#define \fBDREG_GPS_SAT_11_12\fP   0x88"
.br
.RI "GPS satellites 11 and 12\&. "
.ti -1c
.RI "#define \fBDREG_GYRO_BIAS_X\fP   0x89"
.br
.RI "Gyroscope X-axis bias\&. "
.ti -1c
.RI "#define \fBDREG_GYRO_BIAS_Y\fP   0x8A"
.br
.RI "Gyroscope Y-axis bias\&. "
.ti -1c
.RI "#define \fBDREG_GYRO_BIAS_Z\fP   0x8B"
.br
.RI "Gyroscope Z-axis bias\&. "
.ti -1c
.RI "#define \fBGET_FW_REVISION\fP   0xAA"
.br
.RI "Get firmware revision\&. "
.ti -1c
.RI "#define \fBFLASH_COMMIT\fP   0xAB"
.br
.RI "Write all configuration settings to FLASH\&. "
.ti -1c
.RI "#define \fBRESET_TO_FACTORY\fP   0xAC"
.br
.RI "Reset to factory defaults\&. "
.ti -1c
.RI "#define \fBZERO_GYROS\fP   0xAD"
.br
.RI "Zero gyroscopes (keep flat) "
.ti -1c
.RI "#define \fBSET_HOME_POSITION\fP   0xAE"
.br
.RI "Set home position\&. "
.ti -1c
.RI "#define \fBSET_MAG_REFERENCE\fP   0xB0"
.br
.RI "Set magnetic reference\&. "
.ti -1c
.RI "#define \fBCALIBRATE_ACCELEROMETERS\fP   0xB1"
.br
.RI "Calibrate accelerometers (keep flat) "
.ti -1c
.RI "#define \fBRESET_EKF\fP   0xB3"
.br
.RI "Reset the Extended Kalman Filter\&. "
.ti -1c
.RI "#define \fBREAD_DELAY\fP   100"
.br
.ti -1c
.RI "#define \fBBUFFER_LENGTH\fP   128"
.br
.ti -1c
.RI "#define \fBGET_PACKET_ATTEMPS\fP   5"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBUM7_packet_struct\fP \fBUM7_packet\fP"
.br
.RI "Structure for holding received packet information\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBextract_bits\fP (uint8_t byte, uint8_t start_bit, uint8_t num_bits)"
.br
.RI "Helper function to extract bits from a byte\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the \fBRedshift_UML7\fP class, which provides an interface to the UM7 sensor\&. 

This file contains the definitions, constants, and declarations required to interact with the UM7 sensor\&. The UM7 sensor is a high-performance orientation sensor that provides data such as gyroscope, accelerometer, magnetometer, GPS, and orientation (yaw, pitch, roll)\&. The \fBRedshift_UML7\fP class facilitates communication with the sensor over a serial interface and provides methods to retrieve and process sensor data\&.

.PP
\fBAuthor\fP
.RS 4
Vojtěch Giesl 
.RE
.PP
\fBDate\fP
.RS 4
03/2025 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "uint8_t extract_bits (uint8_t byte, uint8_t start_bit, uint8_t num_bits)"

.PP
Helper function to extract bits from a byte\&. 
.PP
\fBParameters\fP
.RS 4
\fIbyte\fP The byte to extract bits from\&. 
.br
\fIstart_bit\fP The starting bit position\&. 
.br
\fInum_bits\fP The number of bits to extract\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Extracted bits as a uint8_t\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RedshiftLabls UM7 library from the source code\&.
