{
 "title": "Tracking - esp32",
 "tags": [
  "tracking",
  "esp32"
 ],
 "time": { "from": "2025-04-06T11:51:28.982Z", "to": "2025-04-06T12:45:57.599Z" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Zařízení",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"main\", tag: \"device\", start: v.timeRangeStart, stop: v.timeRangeStop)"
   }
  ]
 },
 "panels": [
  {
   "title": "Poslední známá konfigurace zařízení",
   "type": "stat",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /config.*/)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> last()\n\n"
    }
   ]
  },
  {
   "title": "GPS measurements",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uml7_car_movement_gps_latitude\" or r[\"_measurement\"] == \"uml7_car_movement_gps_longitude\" or r[\"_measurement\"] == \"uml7_car_movement_gps_speed\")\n  |> filter(fn: (r) => r[\"device\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r._value != 0)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Can messages",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"can_message\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"id\"])\n  |> keep(columns: [\"id\", \"_value\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Stav senzoru UML7",
   "type": "stat",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /health_.*/)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> last()"
    }
   ]
  },
  {
   "title": "GPS measurements",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uml7_car_movement_gps_latitude\" or r[\"_measurement\"] == \"uml7_car_movement_gps_longitude\" or r[\"_measurement\"] == \"uml7_car_movement_gps_speed\")\n  |> filter(fn: (r) => r[\"device\"] =~ /${device:regex}/)\n  |> filter(fn: (r) => r._value != 0)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Gyroscope measurements",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /.*gyro.*/)\n  |> filter(fn: (r) => r[\"device\"] =~ /${device:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Accel measurements",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /.*accel.*/)\n  |> filter(fn: (r) => r[\"device\"] =~ /${device:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Magnetic measurements",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /.*mag.*/ )\n  |> filter(fn: (r) => r[\"device\"] =~ /${device:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "GPS measurements",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /.*gps_.*/ )\n  |> filter(fn: (r) => r[\"device\"] =~ /${device:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> group()"
    }
   ]
  }
 ]
}