apiVersion: 1

# list of datasource's that should be deleted from the database
deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    is_default: true
    url: http://influxdb:8086
    basicAuth: false
    jsonData:
      queryLanguage: flux
      defaultBucket: main
      httpMode: POST
      organization: GIESL
      version: Flux
    secureJsonData:
      token: viGZA7zu-lkoFQpplbBZjTezXAKvmxRwziZFcU-xzF0Qq_wiERbCc6tbFVQ7cDW2WlHOunAALlUuyGdlgU0FDg==
    editable: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: eQG7hSXiZTn7e0E7aDkcSec3
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      postgresVersion: 1300


